Fed up with workloads
In CI, we keep seeing errors like:

```
Workload installation failed: Failed to validate package signing.

Verifying Microsoft.NET.Runtime.MonoAOTCompiler.Task.6.0.2-mauipre.1.22102.15

error: NU3004: The package is not signed.

Package signature validation failed.
```

This is presumably happening because NuGet.config references multiple
feeds, some of which have signed versions of workload packages, and some
of which have unsigned versions.

We can untangle this later. For now, change EditorFeatures.Cocoa to
target `net6.0` instead of `net6.0-macos`, and manually reference the
assemblies it needs from the macos SDK and the VS editor.