Add separate error for disallowed members in global namespace (#81221)
Fixes https://github.com/dotnet/roslyn/issues/81141
Adds a dedicated error, for when members are defined next to statements
in the global namespace. The current error `error CS0116: A namespace
cannot directly contain members such as fields, methods or statements`
can be confusing, as statements (including local functions) can be
defined as top level statements, but not any other members. I could not
figure any suitable single message for both global statements and a
namespace, therefore i split the message into two separate ones.