Track structs piecewise in local functions (#15585)
The problem is demonstrated by the following test case:

```
struct S { public int X, Y; }

class C
{
    public static void Main()
    {
        S s;
        s.X = 5;
        void Local()
        {
          s.Y = 10;
          System.Console.WriteLine(s);
        }
        Local(); // error CS0165: Use of unassigned local variable 's'
    }
}
```

Definite assignment should allow structs to be assigned piecewise
through a local function. The problem is that printing `s` is normally
regarded as a use of `s`, not its constituent fields. This causes the
analysis to effectively lose information about s.Y being assigned.

The fix is, when recording captured reads of possibly unassigned
structs in a local function, recursively record the possibly unassigned
constituent fields, rather than the struct variable.

Fixes #14097