Reverted change due to CI build error
CI build fails with:

Output\OutputClassifierProvider.cs(26,52): error CS0649: Field
'OutputClassifierProvider._classificationRegistry' is never assigned to,
and will always have its default value null