Fix: LINQ implicit anonymous type property allows stack-only type, causing runtime TypeLoadException (#84485)
Fix #39604
Fix #72945

C# LINQ queries implicitly generate anonymous types in certain
scenarios. While the fields of these anonymous types reside on the heap,
the compiler previously accepted stack-only types (such as `ref
struct`s) without emitting any errors or warnings. At runtime, loading
such code immediately triggers a `TypeLoadException`, causing the
program to crash.

For example, the following code assigns a `ref struct` to a range
variable using a LINQ `let` clause and compiles successfully:

~~~cs
var array = new int[] { 1, 2, 3 };
var all = from i in array
          let span = array.AsSpan()
          select span[i];
Console.WriteLine(all.Sum());
~~~

In reality, this code stores the `ref struct` in a field of a
compiler-generated anonymous type. Running the above code immediately
throws a `TypeLoadException`:

> System.TypeLoadException: A ByRef or ByRef-like type cannot be used as
the type for an instance field in a non-ByRef-like type.
> MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
> MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags
invokeAttr)

This PR addresses this class of issues by reporting a compile-time error
whenever a LINQ clause attempts to lift a stack-only type into an
anonymous type field, allowing developers to catch the problem early.